using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;

namespace ObjectDisposedReproDotNet48
{
    //DumbClient is just an experiment to I used to validate that the OE error
    //  wasn't being generated by the server side.

    internal class DumbClient
    {
        internal static void Go()
        {
            var requestData = Encoding.ASCII.GetBytes(@"GET / HTTP/1.1
Cache-Control: no-cache
Host: winbox:18093

");
            using var socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
            socket.Connect("127.0.0.1", 18093);

            var sentCount = 0;
            while (sentCount < requestData.Length)
            {
                sentCount += socket.Send(requestData, sentCount, requestData.Length - sentCount, SocketFlags.None);
            }

            byte[] responseBytes = new byte[1024];

            var totalReceived = 0;

            while (true)
            {
                var receivedCount = socket.Receive(responseBytes);
                totalReceived += receivedCount;

                if (totalReceived >= 2443)
                    break;

            }

            socket.Close();
        }
    }
}
